const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    SET_PEOPLE: 'SET_PEOPLE',
    FETCH_PEOPLE: 'FETCH_PEOPLE',
    FETCH_PEOPLE_ERROR: 'FETCH_PEOPLE_ERROR',
    FETCH_MATCHES_SUCCESS: 'FETCH_MATCHES',
    FETCH_MATCHES_ERROR: 'FETCH_MATCHES_ERROR',
    CREATE_MATCHES_SUCCESS: 'CREATE_MATCHES',
    CREATE_MATCHES_ERROR: 'CREATE_MATCHES_ERROR'
}

export default Constants;